spring.application.name=mymoodapp

#Postgresのドライバーの設定
spring.datasource.driver-class-name=org.postgresql.Driver

#DBへの接続URLを設定
spring.datasource.url=jdbc:postgresql://localhost:5432/springdb

#DB接続のためのユーザー名を設定
spring.datasource.username=springuser

#DB接続のためのパスワードを設定
spring.datasource.password=p@ss

#SQLスクリプトの初期値モードを設定
spring.sql.init.mode=always