spring.application.name=mymoodapp

#Postgresのドライバーの設定
spring.datasource.driver-class-name=org.postgresql.Driver

#DBへの接続URLを設定
spring.datasource.url=jdbc:postgresql://localhost:5432/mymooddb

#application-local.propertiesをSpringが読み込む
spring.profiles.active=local

#SQLスクリプトの初期値モードを設定
spring.sql.init.mode=always